spring.application.name=demo
# Datos de conexión

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo
spring.datasource.username=postgres
spring.datasource.password=0278

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# 2. MOSTRAR SQL

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:ClaveSuperSecretaPorDefectoParaLocalDeMasDe32Caracteres}
